intents = {
    'recommend_songs': [
        'recommend songs',
        'recommend some songs',
        'song recommendations',
        'music recommendations',
        'i need new music',
        'suggest songs',
        'suggest some music',
        'i need new songs',
        'recommend music for me',
        'i want song recommendations',
        'can you recommend songs',
        'give me song recommendations',
    ],
    'artist_information': [
        'who is',
        'tell me about artist',
        'tell me about the artist',
        'artist information for',
        'information about',
        'details about artist',
        'give me info about',
    ],
    'song_information': [
        'tell me about the song',
        'song information for',
        'information about song',
        'details about song',
        'give me info about the song',
    ],
    'trending_songs': [
        'what are the current trending songs',
        'list the top songs right now',
        'which songs are popular this month',
        'show me trending songs',
        'popular songs right now',
    ]
}

responses = {
    "song information": "To get information about a specific song, please ask: 'Tell me about [song name]'",
    "artist information": "To get information about an artist, please ask: 'Who is [artist name]?'",
    "recommend songs": "I can recommend songs based on your preferences. Just say 'Recommend some songs for me'",
    "trending songs": "To get a list of trending songs from the last month, ask 'What are the current trending songs?'",
    "song information": "To get information about a specific song, please ask: 'Tell me about [song name]'",
    "artist information": "To get information about an artist, please ask: 'Who is [artist name]?'",
    "album information": "To get information about an album, please ask: 'Tell me about the album [album name]'",
    "recommend songs": "I can recommend songs based on your preferences. Just say 'Recommend some songs for me'",
    "trending songs": "To get a list of trending songs from the last month, ask 'What are the current trending songs?'",
    "genre": "To find songs in a specific genre, ask 'What are some popular [genre] songs?'",
    "release date": "To find songs released on a specific date, ask 'What songs were released on [date]?'",
    "popular songs": "To find popular songs by an artist, ask 'What are [artist name]'s most popular songs?'",
    "music features": "I can provide information about various music features like valence, acousticness, danceability, energy, speechiness, tempo, and more. Ask about a specific feature for more details.",
    "valence": "Valence in music describes the musical positiveness conveyed by a track. High valence sounds more positive (happy, cheerful), while low valence sounds more negative (sad, angry).",
    "acousticness": "Acousticness measures how acoustic a song is. Higher values indicate more acoustic sounds, while lower values suggest more electronic elements.",
    "danceability": "Danceability describes how suitable a track is for dancing based on musical elements like tempo, rhythm stability, beat strength, and overall regularity.",
    "energy": "Energy represents a perceptual measure of intensity and activity. Energetic tracks feel fast, loud, and noisy.",
    "instrumentalness": "Instrumentalness predicts whether a track contains no vocals. The closer the instrumentalness value is to 1.0, the greater likelihood the track contains no vocal content.",
    "loudness": "Loudness is the quality of a sound that is the primary psychological correlate of physical strength (amplitude). Values typically range between -60 and 0 db.",
    "popularity": "Popularity is a value between 0 and 100, with 100 being the most popular. It's based on the total number of plays and how recent those plays are.",
    "speechiness": "Speechiness detects the presence of spoken words in a track. Values above 0.66 describe tracks that are probably made entirely of spoken words, values between 0.33 and 0.66 describe tracks that may contain both music and speech, and values below 0.33 most likely represent music and other non-speech-like tracks.",
    "tempo": "Tempo represents the overall estimated tempo of a track in beats per minute (BPM). To find songs within a specific tempo range, ask 'What are some songs with tempo between [min] and [max] BPM?'",
}